'use client';

import { useEffect, useMemo, useState } from 'react';
import Image from 'next/image';
import { Edit3, ImageIcon, Route, Save, Trash2, Truck } from 'lucide-react';
import toast from 'react-hot-toast';
import Modal from '@ui/Modal';
import { useAdminPricingRules, useDeletePricingRule, useUpdatePricingRule } from '@hooks/useBookingPricingRules';
import { useAdminItemCatalog } from '@hooks/useItems';
import { getTruckImageSrc } from '@utils/truckVisuals';
import { buildItemVariantOptions, describeAllowanceRows } from '@utils/freeAllowanceDisplay';

const SERVICES = [['local_shifting', 'Local shifting'], ['intercity_moving', 'Intercity moving'], ['porter_labour_service', 'Labour & Vehicle']];
const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];
const blankRule = { serviceType: 'local_shifting', name: '', currency: 'INR', basePrice: 0, freeItemAllowance: [], distancePricing: { enabled: true, slabs: [] }, floorPricing: { enabled: true, slabs: [] }, liftPricing: { enabled: true, withLiftCharge: 0, withoutLiftCharge: 0 }, labourPricing: { enabled: false, trucks: [], employeeRates: [], hourlyRates: [] }, isActive: true, sortOrder: 1 };

export default function BookingPricingManagerPage() {
  const [filters, setFilters] = useState({ serviceType: 'all', isActive: 'all' });
  const [editor, setEditor] = useState(null);
  const { data = [], isLoading, isError, refetch } = useAdminPricingRules(filters);
  const { data: itemCatalog = [] } = useAdminItemCatalog({});
  const updateRule = useUpdatePricingRule();
  const deleteRule = useDeletePricingRule();
  const rules = useMemo(() => Array.isArray(data) ? data : [], [data]);
  const itemOptions = useMemo(() => buildItemVariantOptions(itemCatalog), [itemCatalog]);

  const save = async (payload) => {
    try {
      if (!editor?._id) throw new Error('Pricing rule must exist in backend first.');
      await updateRule.mutateAsync({ id: editor._id, data: payload });
      toast.success('Pricing rule updated');
      setEditor(null);
    } catch (error) {
      toast.error(error.message);
    }
  };

  return <div className="space-y-6">
    <header>
      <p className="text-xs font-semibold uppercase tracking-[.18em] text-sky-600">API pricing rules</p>
      <h1 className="mt-1 text-2xl font-bold text-slate-900">Booking Pricing Manager</h1>
      <p className="mt-1 max-w-3xl text-sm font-medium leading-6 text-slate-500">Manage base price, free allowance, distance slabs, lift-aware floor charges, trucks, and hourly rates from backend rules.</p>
    </header>
    <div className="flex flex-wrap gap-2 rounded-2xl border border-sky-100 bg-white p-3 shadow-sm">
      <select value={filters.serviceType} onChange={(event) => setFilters({ ...filters, serviceType: event.target.value })} className="admin-field max-w-56"><option value="all">All services</option>{SERVICES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>
      <select value={filters.isActive} onChange={(event) => setFilters({ ...filters, isActive: event.target.value })} className="admin-field max-w-48"><option value="all">All status</option><option value="true">Active</option><option value="false">Inactive</option></select>
    </div>
    {isLoading ? <State text="Loading pricing rules..." /> : isError ? <State text="Could not load pricing rules." action={refetch} /> : rules.length === 0 ? <State text="No pricing rules found from API." /> : <div className="grid gap-4 xl:grid-cols-2">{rules.map((rule) => <RuleCard key={rule._id} rule={rule} itemOptions={itemOptions} onEdit={() => setEditor(rule)} onToggleActive={async () => { try { await updateRule.mutateAsync({ id: rule._id, data: { isActive: rule.isActive === false } }); toast.success(`${rule.name} ${rule.isActive === false ? 'activated' : 'deactivated'}`); } catch (error) { toast.error(error.message); } }} onDelete={async () => { if (!window.confirm(`Deactivate ${rule.name}?`)) return; try { await deleteRule.mutateAsync(rule._id); toast.success('Pricing rule deactivated'); } catch (error) { toast.error(error.message); } }} />)}</div>}
    <RuleEditor record={editor} itemOptions={itemOptions} onClose={() => setEditor(null)} onSave={save} busy={updateRule.isPending} />
  </div>;
}

function RuleCard({ rule, itemOptions = [], onEdit, onToggleActive, onDelete }) {
  const labour = rule.serviceType === 'porter_labour_service';
  const allowance = describeAllowanceRows(rule.freeItemAllowance || [], itemOptions);
  return <article className="rounded-2xl border border-sky-100 bg-white p-5 shadow-sm">
    <div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-sky-600">{labour ? <Truck className="h-5 w-5" /> : <Route className="h-5 w-5" />}</span><div><h2 className="font-semibold text-slate-900">{rule.name}</h2><p className="text-xs font-medium text-slate-400">{SERVICES.find(([value]) => value === rule.serviceType)?.[1] || rule.serviceType}</p></div></div><button type="button" onClick={onToggleActive} className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase transition ${rule.isActive === false ? 'bg-slate-100 text-slate-500 hover:bg-slate-200' : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'}`}>{rule.isActive === false ? 'Inactive' : 'Active'}</button></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Base price" value={`Rs ${Number(rule.basePrice || 0).toLocaleString('en-IN')}`} /><Metric label={labour ? 'Truck options' : 'Distance ranges'} value={labour ? (rule.labourPricing?.trucks || []).length : (rule.distancePricing?.slabs || []).length} /><Metric label={labour ? 'Hourly rates' : 'Floor ranges'} value={labour ? (rule.labourPricing?.hourlyRates || []).length : (rule.floorPricing?.slabs || []).length} /></div>
    {labour ? <div className="mt-4 grid gap-3"><Preview title="Distance pricing" rows={rule.distancePricing?.enabled ? (rule.distancePricing?.slabs || []).map(distanceRow) : ['Disabled']} /><TruckPreview trucks={rule.labourPricing?.trucks || []} /><Preview title="Employee allowance" rows={(rule.labourPricing?.employeeRates || []).map((item) => `${item.employees} employee(s): ${item.isFree ? 'Included in base' : 'Custom selection'}`)} /><Preview title="Hourly rate set" rows={(rule.labourPricing?.hourlyRates || []).map(labourHourRow)} /></div> : <div className="mt-4 grid gap-3"><Preview title="Free item allowance" rows={allowance.length ? allowance : ['No allowance set']} /><Preview title="Distance price set" rows={(rule.distancePricing?.slabs || []).map(distanceRow)} /><Preview title="Floor price set" rows={(rule.floorPricing?.slabs || []).map(floorRow)} /></div>}
    <div className="mt-5 flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-4">{labour && <button onClick={onToggleActive} className={`inline-flex items-center rounded-lg border px-3 py-2 text-xs font-semibold ${rule.isActive === false ? 'border-emerald-100 text-emerald-600' : 'border-slate-200 text-slate-600'}`}>{rule.isActive === false ? 'Activate Labour' : 'Set Labour Inactive'}</button>}<button onClick={onEdit} className="inline-flex items-center gap-1.5 rounded-lg border border-sky-100 px-3 py-2 text-xs font-semibold text-sky-700"><Edit3 className="h-3.5 w-3.5" />Edit</button><button onClick={onDelete} disabled={rule.isActive === false} className="inline-flex items-center gap-1.5 rounded-lg border border-red-100 px-3 py-2 text-xs font-semibold text-red-500 disabled:opacity-35"><Trash2 className="h-3.5 w-3.5" />Deactivate</button></div>
  </article>;
}

function RuleEditor({ record, itemOptions = [], onClose, onSave, busy }) {
  const [form, setForm] = useState(blankRule);
  useEffect(() => { if (record) setForm(hydrateRule(record)); }, [record]);
  if (!record) return null;
  const labour = form.serviceType === 'porter_labour_service';
  const submit = (event) => {
    event.preventDefault();
    onSave({ ...form, basePrice: num(form.basePrice), freeItemAllowance: labour ? [] : normalizeRows(form.freeItemAllowance, ['quantity']), distancePricing: { ...form.distancePricing, enabled: labour ? form.distancePricing?.enabled === true : true, slabs: buildDistanceSlabs(form.distancePricing?.slabs) }, floorPricing: { ...form.floorPricing, enabled: !labour, slabs: buildFloorSlabs(form.floorPricing?.slabs) }, liftPricing: { ...form.liftPricing, enabled: !labour && form.liftPricing?.enabled !== false, withLiftCharge: 0, withoutLiftCharge: 0 }, labourPricing: { ...form.labourPricing, enabled: labour, trucks: withOrder(normalizeRows(form.labourPricing?.trucks, ['price', 'capacityKg']).map((item) => ({ ...item, key: slug(item.name), image: String(item.image || '').trim(), isActive: true }))), employeeRates: withOrder(normalizeRows(form.labourPricing?.employeeRates, ['employees']).map((item) => ({ ...item, label: `${item.employees} employee${Number(item.employees) > 1 ? 's' : ''}`, price: 0, isActive: true }))), hourlyRates: withOrder(normalizeRows(form.labourPricing?.hourlyRates, ['hours', 'price']).map((item) => ({ ...item, label: `${item.hours} hour${Number(item.hours) > 1 ? 's' : ''}`, isActive: true }))) } });
  };

  return <Modal isOpen onClose={onClose} title="Edit pricing rule" size="xl"><form onSubmit={submit} className="space-y-5">
    <Section title="1. Service and base price" desc="Service comes from backend. Update base amount and rule details."><div className="grid gap-4 sm:grid-cols-2"><Field label="Service"><input value={SERVICES.find(([value]) => value === form.serviceType)?.[1] || form.serviceType} disabled className="admin-field bg-slate-50" /></Field><Field label="Rule name"><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="admin-field" /></Field><Field label="Base price in rupees"><input type="number" min="0" value={form.basePrice} onChange={(event) => setForm({ ...form, basePrice: event.target.value })} className="admin-field" /></Field><Field label="Currency"><input value={form.currency} onChange={(event) => setForm({ ...form, currency: event.target.value })} className="admin-field" /></Field></div></Section>
    {!labour && <FreeAllowance rows={form.freeItemAllowance || []} itemOptions={itemOptions} onChange={(rows) => setForm({ ...form, freeItemAllowance: rows })} />}
    {!labour && <><SimpleRows title="3. Distance price set" desc="Only upper KM is visible. From KM and order are generated automatically." rows={form.distancePricing?.slabs || []} columns={[['label', 'Range name'], ['toKm', 'Up to KM'], ['ratePerKm', 'Rs per KM'], ['isFree', 'Free?']]} empty={{ label: '', toKm: '', ratePerKm: 0, isFree: false }} onChange={(rows) => setForm({ ...form, distancePricing: { ...form.distancePricing, slabs: rows } })} /><FloorRows rows={form.floorPricing?.slabs || []} onChange={(rows) => setForm({ ...form, floorPricing: { ...form.floorPricing, slabs: rows } })} /><Section title="5. Lift pricing mode" desc="Floor rows hold both lift and without-lift prices. Disable only if lift selection should not affect floor charge."><Field label="Lift-based floor charges"><select value={String(form.liftPricing?.enabled !== false)} onChange={(event) => setForm({ ...form, liftPricing: { ...form.liftPricing, enabled: event.target.value === 'true' } })} className="admin-field"><option value="true">Enabled</option><option value="false">Disabled</option></select></Field></Section></>}
    {labour && <><Section title="2. Distance pricing" desc="Enable this only if Labour & Vehicle quote should include KM charge."><label className="mb-4 flex items-center gap-2 rounded-xl border border-sky-100 bg-sky-50/60 p-3 text-sm font-semibold text-slate-700"><input type="checkbox" checked={form.distancePricing?.enabled === true} onChange={(event) => setForm({ ...form, distancePricing: { ...form.distancePricing, enabled: event.target.checked } })} className="accent-sky-600" />Enable distance pricing for this service</label>{form.distancePricing?.enabled === true && <SimpleRows title="Distance price set" desc="Only upper KM is visible. From KM and order are generated automatically." rows={form.distancePricing?.slabs || []} columns={[['label', 'Range name'], ['toKm', 'Up to KM'], ['ratePerKm', 'Rs per KM'], ['isFree', 'Free?']]} empty={{ label: '', toKm: '', ratePerKm: 0, isFree: false }} onChange={(rows) => setForm({ ...form, distancePricing: { ...form.distancePricing, slabs: rows } })} />}</Section><TruckRows rows={form.labourPricing?.trucks || []} onChange={(rows) => setForm({ ...form, labourPricing: { ...form.labourPricing, trucks: rows } })} /><EmployeeRows rows={form.labourPricing?.employeeRates || []} onChange={(rows) => setForm({ ...form, labourPricing: { ...form.labourPricing, employeeRates: rows } })} /><SimpleRows title="5. Hourly rate set" desc="Set duration packages and mark how many hours are included in the base price." rows={form.labourPricing?.hourlyRates || []} columns={[['hours', 'Hours'], ['price', 'Price'], ['isFree', 'Free in base?']]} empty={{ hours: 1, price: 0, isFree: false }} onChange={(rows) => setForm({ ...form, labourPricing: { ...form.labourPricing, hourlyRates: rows } })} /></>}
    <label className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm font-medium text-slate-600"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} className="accent-sky-600" />Active rule</label>
    <div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-600">Cancel</button><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-sky-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4" />Save rule</button></div>
  </form></Modal>;
}

function hydrateRule(rule) { return { ...blankRule, ...rule, distancePricing: { ...blankRule.distancePricing, ...rule.distancePricing, slabs: (rule.distancePricing?.slabs || []).map(({ label, toKm, ratePerKm, isFree }) => ({ label, toKm: toKm ?? '', ratePerKm, isFree })) }, floorPricing: { ...blankRule.floorPricing, ...rule.floorPricing, slabs: (rule.floorPricing?.slabs || []).map(({ label, toFloor, charge, withLiftCharge, withoutLiftCharge, isFree }) => ({ label, toFloor: toFloor ?? '', withLiftCharge: withLiftCharge ?? charge ?? 0, withoutLiftCharge: withoutLiftCharge ?? charge ?? 0, isFree: Boolean(isFree) })) }, labourPricing: { ...blankRule.labourPricing, ...rule.labourPricing, trucks: rule.labourPricing?.trucks || [], employeeRates: rule.labourPricing?.employeeRates || [], hourlyRates: rule.labourPricing?.hourlyRates || [] } }; }
function buildDistanceSlabs(rows = []) { let from = 0; return rows.map((row, index) => { const last = index === rows.length - 1; let to = row.toKm === '' || row.toKm === null || row.toKm === undefined ? null : num(row.toKm); if (to !== null && to <= from) to = last ? null : Math.round((from + 0.1) * 10) / 10; const slab = { label: row.label || `${from}-${to ?? '+'} km`, fromKm: from, toKm: to, ratePerKm: num(row.ratePerKm), isFree: Boolean(row.isFree), sortOrder: index + 1 }; if (to !== null) from = to; return slab; }); }
function buildFloorSlabs(rows = []) { let from = 1; return rows.map((row, index) => { const last = index === rows.length - 1; let to = row.toFloor === '' || row.toFloor === null || row.toFloor === undefined ? null : num(row.toFloor); if (to !== null && to < from) to = last ? null : from; const withoutLiftCharge = num(row.withoutLiftCharge); const withLiftCharge = num(row.withLiftCharge); const slab = { label: row.label || `${from}-${to ?? '+'} floor`, fromFloor: from, toFloor: to, charge: withoutLiftCharge, withLiftCharge, withoutLiftCharge, isFree: Boolean(row.isFree), sortOrder: index + 1 }; if (to !== null) from = to + 1; return slab; }); }
function FreeAllowance({ rows, itemOptions = [], onChange }) {
  const [selectedOption, setSelectedOption] = useState(itemOptions[0] ? `${itemOptions[0].itemId}:${itemOptions[0].sizeKey}` : '');
  useEffect(() => {
    if (!selectedOption && itemOptions[0]) setSelectedOption(`${itemOptions[0].itemId}:${itemOptions[0].sizeKey}`);
  }, [itemOptions, selectedOption]);
  const setQuantity = (sizeKey, quantity) => onChange([...rows.filter((item) => item.sizeKey !== sizeKey), { sizeKey, quantity }].sort((a, b) => SIZES.indexOf(a.sizeKey) - SIZES.indexOf(b.sizeKey)));
  const addSelected = () => {
    const option = itemOptions.find((item) => `${item.itemId}:${item.sizeKey}` === selectedOption);
    if (!option) return;
    const current = rows.find((item) => item.sizeKey === option.sizeKey);
    setQuantity(option.sizeKey, Number(current?.quantity || 0) + 1);
  };
  const readableRows = describeAllowanceRows(rows, itemOptions);
  return <Section title="2. Free allowance" desc="Choose item names to add base-price allowance. The pricing engine still stores the existing internal size bucket behind the scenes."><div className="grid gap-3 md:grid-cols-[1fr_auto]"><Field label="Select item to include"><select value={selectedOption} onChange={(event) => setSelectedOption(event.target.value)} className="admin-field">{itemOptions.map((item) => <option key={`${item.itemId}:${item.sizeKey}`} value={`${item.itemId}:${item.sizeKey}`}>{item.label} - {item.group}</option>)}</select></Field><button type="button" onClick={addSelected} disabled={!itemOptions.length} className="mt-5 rounded-xl bg-sky-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Add allowance item</button></div><div className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{SIZES.map((sizeKey) => { const row = rows.find((item) => item.sizeKey === sizeKey) || { sizeKey, quantity: 0 }; const examples = itemOptions.filter((item) => item.sizeKey === sizeKey).slice(0, 2).map((item) => item.name).join(', '); return <Field key={sizeKey} label={examples || allowanceBucketLabel(sizeKey)}><input type="number" min="0" value={row.quantity} onChange={(event) => setQuantity(sizeKey, event.target.value)} className="admin-field" /></Field>; })}</div><div className="mt-4 flex flex-wrap gap-2">{(readableRows.length ? readableRows : ['No allowance set']).map((row, index) => <span key={`${row}-${index}`} className="rounded-lg bg-sky-50 px-2.5 py-1 text-xs font-semibold text-sky-700 ring-1 ring-sky-100">{row}</span>)}</div></Section>;
}
function allowanceBucketLabel(sizeKey) { return { XS: 'Extra small item allowance', S: 'Small item allowance', M: 'Medium item allowance', L: 'Large item allowance', XL: 'Extra large item allowance', XXL: 'Oversized item allowance' }[sizeKey] || 'Item allowance'; }
function FloorRows({ rows, onChange }) { return <Section title="4. Floor price set" desc="Each row has a floor range, price when lift is available, and price when lift is not available."><div className="space-y-2">{rows.map((row, index) => <div key={index} className="grid gap-2 rounded-xl bg-slate-50 p-2 md:grid-cols-[1fr_.8fr_.8fr_.8fr_auto]"><Field label="Range name"><input value={row.label || ''} onChange={(event) => onChange(rows.map((item, rowIndex) => rowIndex === index ? { ...item, label: event.target.value } : item))} className="admin-field bg-white" /></Field><Field label="Up to floor"><input type="number" min="0" value={row.toFloor ?? ''} onChange={(event) => onChange(rows.map((item, rowIndex) => rowIndex === index ? { ...item, toFloor: event.target.value } : item))} className="admin-field bg-white" /></Field><Field label="With lift price"><input type="number" min="0" value={row.withLiftCharge || 0} onChange={(event) => onChange(rows.map((item, rowIndex) => rowIndex === index ? { ...item, withLiftCharge: event.target.value } : item))} className="admin-field bg-white" /></Field><Field label="Without lift price"><input type="number" min="0" value={row.withoutLiftCharge || 0} onChange={(event) => onChange(rows.map((item, rowIndex) => rowIndex === index ? { ...item, withoutLiftCharge: event.target.value } : item))} className="admin-field bg-white" /></Field><div className="flex items-end gap-2"><label className="mb-2 flex h-11 items-center gap-2 rounded-xl border border-sky-100 bg-white px-3 text-xs font-semibold text-slate-600"><input type="checkbox" checked={Boolean(row.isFree)} onChange={(event) => onChange(rows.map((item, rowIndex) => rowIndex === index ? { ...item, isFree: event.target.checked } : item))} className="accent-sky-600" />Free</label><button type="button" onClick={() => onChange(rows.filter((_, rowIndex) => rowIndex !== index))} className="mb-2 h-11 rounded-lg border border-red-100 px-3 text-xs font-semibold text-red-500">Remove</button></div></div>)}<button type="button" onClick={() => onChange([...rows, { label: '', toFloor: '', withLiftCharge: 0, withoutLiftCharge: 0, isFree: false }])} className="rounded-lg bg-sky-50 px-3 py-2 text-xs font-semibold text-sky-700">Add row</button></div></Section>; }
function TruckRows({ rows, onChange }) { return <Section title="3. Truck options" desc="Admin can add, update, or remove truck name, capacity, price, and image URL. Users see image, name, and capacity together."><div className="space-y-3">{rows.map((row, rowIndex) => <div key={rowIndex} className="grid gap-3 rounded-2xl bg-slate-50 p-3 lg:grid-cols-[96px_1fr_auto]"><Image unoptimized src={getTruckImageSrc(row)} alt={row.name || 'Truck'} width={96} height={96} className="h-24 w-24 rounded-xl border border-sky-100 bg-white object-cover" /><div className="grid gap-2 md:grid-cols-2"><Field label="Truck name"><input value={row.name || ''} onChange={(event) => onChange(rows.map((item, index) => index === rowIndex ? { ...item, name: event.target.value } : item))} className="admin-field bg-white" /></Field><Field label="Capacity in kg"><input type="number" min="0" value={row.capacityKg ?? ''} onChange={(event) => onChange(rows.map((item, index) => index === rowIndex ? { ...item, capacityKg: event.target.value } : item))} className="admin-field bg-white" /></Field><Field label="Image URL"><input value={row.image || ''} onChange={(event) => onChange(rows.map((item, index) => index === rowIndex ? { ...item, image: event.target.value } : item))} className="admin-field bg-white" placeholder="https://..." /></Field><Field label="Price"><input type="number" min="0" value={row.price ?? 0} onChange={(event) => onChange(rows.map((item, index) => index === rowIndex ? { ...item, price: event.target.value } : item))} className="admin-field bg-white" /></Field></div><div className="flex flex-row items-center gap-2 lg:flex-col lg:items-stretch lg:justify-end"><label className="flex h-11 items-center gap-2 rounded-xl border border-sky-100 bg-white px-3 text-xs font-semibold text-slate-600"><input type="checkbox" checked={Boolean(row.isFree)} onChange={(event) => onChange(rows.map((item, index) => index === rowIndex ? { ...item, isFree: event.target.checked } : item))} className="accent-sky-600" />Free</label><button type="button" onClick={() => onChange(rows.filter((_, index) => index !== rowIndex))} className="h-11 rounded-lg border border-red-100 bg-white px-3 text-xs font-semibold text-red-500">Remove</button></div></div>)}<button type="button" onClick={() => onChange([...rows, { name: 'Mini truck', capacityKg: 500, image: '', price: 0, isFree: false }])} className="rounded-lg bg-sky-50 px-3 py-2 text-xs font-semibold text-sky-700">Add truck</button></div></Section>; }
function EmployeeRows({ rows, onChange }) { return <Section title="4. Employee allowance" desc="Employee price is not separate. Labour cost comes from hourly rate. Mark only how many employees are included in the base price."><div className="grid gap-3 sm:grid-cols-2">{rows.map((row, rowIndex) => <div key={rowIndex} className={`rounded-2xl border p-4 ${row.isFree ? 'border-emerald-200 bg-emerald-50/70' : 'border-sky-100 bg-sky-50/50'}`}><div className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><Field label="Employees"><input type="number" min="1" value={row.employees ?? ''} onChange={(event) => onChange(rows.map((item, index) => index === rowIndex ? { ...item, employees: event.target.value, price: 0 } : item))} className="admin-field bg-white" /></Field><label className="flex h-11 items-center gap-2 rounded-xl border border-white bg-white px-3 text-xs font-semibold text-slate-700 shadow-sm"><input type="checkbox" checked={Boolean(row.isFree)} onChange={(event) => onChange(rows.map((item, index) => index === rowIndex ? { ...item, isFree: event.target.checked, price: 0 } : item))} className="accent-sky-600" />Free in base</label></div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs font-semibold text-slate-500">Extra employee amount is calculated from hourly rate.</p><button type="button" onClick={() => onChange(rows.filter((_, index) => index !== rowIndex))} className="rounded-lg border border-red-100 bg-white px-3 py-2 text-xs font-semibold text-red-500">Remove</button></div></div>)}</div><button type="button" onClick={() => onChange([...rows, { employees: rows.length + 1, price: 0, isFree: false }])} className="mt-3 rounded-lg bg-sky-50 px-3 py-2 text-xs font-semibold text-sky-700">Add employee tier</button></Section>; }
function SimpleRows({ title, desc, rows, columns, empty, onChange }) { return <Section title={title} desc={desc}><div className="space-y-2">{rows.map((row, rowIndex) => <div key={rowIndex} className="grid gap-2 rounded-xl bg-slate-50 p-2 md:grid-cols-[repeat(4,minmax(0,1fr))_auto]">{columns.map(([key, label]) => key === 'isFree' || key === 'isActive' ? <label key={key} className="mt-5 flex h-11 items-center gap-2 rounded-xl border border-sky-100 bg-white px-3 text-sm font-semibold text-slate-600"><input type="checkbox" checked={Boolean(row[key])} onChange={(event) => onChange(rows.map((item, index) => index === rowIndex ? { ...item, [key]: event.target.checked } : item))} className="accent-sky-600" />{label}</label> : <Field key={key} label={label}><input value={row[key] ?? ''} onChange={(event) => onChange(rows.map((item, index) => index === rowIndex ? { ...item, [key]: event.target.value } : item))} className="admin-field bg-white" /></Field>)}<button type="button" onClick={() => onChange(rows.filter((_, index) => index !== rowIndex))} className="mt-5 rounded-lg border border-red-100 px-3 text-xs font-semibold text-red-500">Remove</button></div>)}<button type="button" onClick={() => onChange([...rows, { ...empty }])} className="rounded-lg bg-sky-50 px-3 py-2 text-xs font-semibold text-sky-700">Add row</button></div></Section>; }
function distanceRow(item) { return `${item.label || `${item.fromKm}-${item.toKm || '+'} km`}: ${item.isFree ? 'Free' : `Rs ${item.ratePerKm}/km`}`; }
function floorRow(item) { return `${item.label || `${item.fromFloor}-${item.toFloor || '+'} floor`}: lift Rs ${Number(item.withLiftCharge ?? item.charge ?? 0).toLocaleString('en-IN')} / no lift Rs ${Number(item.withoutLiftCharge ?? item.charge ?? 0).toLocaleString('en-IN')}`; }
function withOrder(rows = []) { return rows.map((row, index) => ({ ...row, sortOrder: index + 1 })); }
function normalizeRows(rows = [], numeric = []) { return rows.map((row) => Object.fromEntries(Object.entries(row).map(([key, value]) => [key, numeric.includes(key) ? num(value) : value]))); }
function slug(value = '') { return String(value).trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'vehicle'; }
function num(value) { return Number.isFinite(Number(value)) ? Number(value) : 0; }
function Section({ title, desc, children }) { return <section className="rounded-2xl border border-sky-100 bg-white p-4"><h3 className="text-sm font-semibold text-slate-800">{title}</h3><p className="mb-4 mt-1 text-xs font-medium leading-5 text-slate-500">{desc}</p>{children}</section>; }
function Metric({ label, value }) { return <div className="rounded-xl bg-sky-50 p-3"><p className="text-[11px] font-semibold uppercase tracking-wide text-sky-600">{label}</p><p className="mt-1 text-lg font-semibold text-slate-900">{value}</p></div>; }
function TruckPreview({ trucks = [] }) { return <div className="rounded-xl border border-sky-100 bg-sky-50/45 p-3"><p className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide text-sky-600"><ImageIcon className="h-3.5 w-3.5" />Truck options</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{(trucks.length ? trucks : [{}]).slice(0, 6).map((truck, index) => <div key={truck._id || truck.key || index} className="flex items-center gap-3 rounded-xl bg-white p-2 ring-1 ring-sky-100"><Image unoptimized src={getTruckImageSrc(truck)} alt={truck.name || 'Truck'} width={64} height={56} className="h-14 w-16 shrink-0 rounded-lg object-cover" /><div className="min-w-0"><strong className="block truncate text-xs text-slate-800">{truck.name || 'Truck not configured'}</strong><span className="block text-[11px] font-semibold text-slate-500">{truck.capacityKg ? `${Number(truck.capacityKg).toLocaleString('en-IN')} kg` : truck.capacityLabel || 'Capacity not set'}</span><span className="block text-[11px] font-semibold text-sky-600">{truck.isFree ? 'Base included, ' : ''}custom Rs {Number(truck.price || 0).toLocaleString('en-IN')}</span></div></div>)}</div></div>; }
function Preview({ title, rows = [] }) { return <div className="rounded-xl border border-sky-100 bg-sky-50/45 p-3"><p className="text-[11px] font-semibold uppercase tracking-wide text-sky-600">{title}</p><div className="mt-2 flex flex-wrap gap-1.5">{(rows.length ? rows : ['Not configured']).slice(0, 8).map((row, index) => <span key={`${row}-${index}`} className="rounded-lg bg-white px-2 py-1 text-xs font-medium text-slate-600 ring-1 ring-sky-100">{row}</span>)}</div></div>; }
function labourHourRow(item) { return `${item.hours} hour: ${item.isFree ? 'Included in base, ' : ''}custom Rs ${Number(item.price || 0).toLocaleString('en-IN')}`; }
function State({ text, action }) { return <div className="rounded-2xl border border-dashed border-sky-200 p-12 text-center text-sm font-medium text-slate-400">{text}{action && <button onClick={action} className="ml-2 font-semibold text-sky-600">Try again</button>}</div>; }
function Field({ label, children }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</span>{children}</label>; }
